// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNL0H5MabrnrVSxpZDyXIhQcvMGBgBxzU',
    appId: '1:736204319157:web:df74f8eb864a5f00f591fc',
    messagingSenderId: '736204319157',
    projectId: 'jobendear-ae2f3',
    authDomain: 'jobendear-ae2f3.firebaseapp.com',
    storageBucket: 'jobendear-ae2f3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4fQik7tdHT7xq-GOBY80hD1ZDATkLpD0',
    appId: '1:736204319157:android:c717feef8c2ce6f9f591fc',
    messagingSenderId: '736204319157',
    projectId: 'jobendear-ae2f3',
    storageBucket: 'jobendear-ae2f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf0i-ijLAE0ShypXA0HqsEpuW2LxUk9oQ',
    appId: '1:736204319157:ios:ebce5d3aab5977a5f591fc',
    messagingSenderId: '736204319157',
    projectId: 'jobendear-ae2f3',
    storageBucket: 'jobendear-ae2f3.appspot.com',
    iosClientId: '736204319157-23ie0thn1pauiqf492uml4fqo16ve9is.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobEndear',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf0i-ijLAE0ShypXA0HqsEpuW2LxUk9oQ',
    appId: '1:736204319157:ios:ebce5d3aab5977a5f591fc',
    messagingSenderId: '736204319157',
    projectId: 'jobendear-ae2f3',
    storageBucket: 'jobendear-ae2f3.appspot.com',
    iosClientId: '736204319157-23ie0thn1pauiqf492uml4fqo16ve9is.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobEndear',
  );
}
